- name: update the system
  become: yes
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install some common tools and core dependencies
  become: yes
  pacman:
    name:
      - archlinux-keyring
      - ansible
      - base-devel
      - curl
      - git
      - htop
      - make
      - neofetch
      - rsync
      - wget
      - zsh
    state: present

- import_tasks: aur.yml
- import_tasks: python.yml
- import_tasks: editors.yml
- import_tasks: docker.yml
- import_tasks: users.yml
- import_tasks: entropy.yml

