- name: Main IIOT user
  become: yes
  user:
    name: "{{iiot_user}}"
    groups: wheel, docker
    append: yes
    shell: /bin/zsh

- name: Backup IIOT user
  become: yes
  user:
    name: bro
    groups: wheel
    append: yes
