version: '3.4'
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    expose:
      - "1883"

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer/data:/data

  influxdb:
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influx.env
    volumes:
      - ./data/influx/data:/var/lib/influxdb
      - ./backups/influx/db:/var/lib/influxdb/backup

