version: '3.4'
services:
  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    expose:
      - "1883"

  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

